CREATE TABLE IF NOT EXISTS "department_DS" (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "faculty_DS" (
    faculty_id VARCHAR(50) PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    date_of_birth DATE,
    department_id INTEGER NOT NULL,
    designation VARCHAR(255) NOT NULL,
    joining_date DATE,
    courses_taught TEXT,
    experience_history TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'Active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_faculty_department FOREIGN KEY (department_id)
        REFERENCES "department_DS" (department_id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_faculty_ds_email ON "faculty_DS" (email);
CREATE INDEX IF NOT EXISTS ix_faculty_ds_department_id ON "faculty_DS" (department_id);
