from collections.abc import Mapping
from typing import Protocol

from models import Department, Faculty


class FacultyRepositoryContract(Protocol):
    def get_all(self) -> list[Faculty]: ...
    def get_by_id(self, faculty_id: str) -> Faculty | None: ...
    def create(self, faculty_data: Mapping[str, object]) -> Faculty: ...
    def update(self, faculty: Faculty, faculty_data: Mapping[str, object]) -> Faculty: ...
    def delete(self, faculty: Faculty) -> None: ...


class DepartmentRepositoryContract(Protocol):
    def get_all(self) -> list[Department]: ...
    def get_by_id(self, department_id: int) -> Department | None: ...
    def create(self, department_data: Mapping[str, object]) -> Department: ...
    def update(self, department: Department, department_data: Mapping[str, object]) -> Department: ...
    def delete(self, department: Department) -> None: ...
